# Generated by Django 5.2.6 on 2025-11-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.pedido')),
            ],
        ),
    ]
